modLoader="javafml"
loaderVersion="[4,)"
license="Apache License version 2.0"

[[mods]]
modId="fake_fps"
version="1.1.9"
displayName="Fake FPS"
displayURL="https://github.com/Dreyka-Oas/Fake-FPS"
logoFile="logo.png"
credits="O.A.S"
authors="Dreyka Oas"
description="Customizable fake FPS display."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.fake_fps]]
    modId="neoforge"
    type="required"
    versionRange="[21.4.101-beta,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.fake_fps]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.4]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration